# Loading Data

In [1]:
import numpy as np
true_val = np.concatenate([ np.ones(15).astype(int) , np.zeros(5).astype(int) ])
true_val

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [2]:
element, counts = np.unique(true_val, return_counts=True)

In [3]:
element

array([0, 1])

In [4]:
counts

array([ 5, 15], dtype=int64)

# Tests

In [5]:
pred = np.ones(20).astype(int)
# pred = np.zeros(20).astype(int)

# Metric Evaluation

In [6]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import balanced_accuracy_score

In [7]:
accuracy_score(true_val , pred )

0.75

In [8]:
print(balanced_accuracy_score( true_val , pred ))

0.5


In [9]:
print(classification_report(true_val , pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.75      1.00      0.86        15

    accuracy                           0.75        20
   macro avg       0.38      0.50      0.43        20
weighted avg       0.56      0.75      0.64        20



c:\softwares\anaconda\envs\demo\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
