# Numpy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:
- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- useful linear algebra, Fourier transform, and random number capabilities

### Objectives
1. Create an array of ‘data’.
2. Perform basic calculations on this data using python math functions.
3. Slice and index the array

# Create an array of 'data'

In [1]:
import numpy as np

In [2]:
# Create a simple array from a list of integers
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
# See how many dimensions the array has
a.ndim

1

In [4]:
# Print out the shape attribute
a.shape

(3,)

In [5]:
# Print out the data type attribute
a.dtype

dtype('int64')

NumPy also provides helper functions for generating arrays of data to save you typing for regularly spaced data. 

* `arange(start, stop, interval)` creates a range of values in the interval `[start,stop)` with `step` spacing.
* `linspace(start, stop, num)` creates a range of `num` evenly spaced values over the range `[start,stop]`.

### arange

In [6]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [7]:
a = np.arange(3, 11)
print(a)

[ 3  4  5  6  7  8  9 10]


In [8]:
a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


### linspace

In [9]:
b = np.linspace(5, 15, 5)
print(b)

[ 5.   7.5 10.  12.5 15. ]


In [10]:
b = np.linspace(2.5, 10.25, 11)
print(b)

[ 2.5    3.275  4.05   4.825  5.6    6.375  7.15   7.925  8.7    9.475
 10.25 ]


### Basic math

In [11]:
a = np.arange(5, 10)
b = np.linspace(3, 4.5, 5)
print(a)
print(b)

[5 6 7 8 9]
[3.    3.375 3.75  4.125 4.5  ]


In [12]:
a+b

array([ 8.   ,  9.375, 10.75 , 12.125, 13.5  ])

In [13]:
a*b

array([15.  , 20.25, 26.25, 33.  , 40.5 ])

### Constants

Numpy has default constants ,we don't need to type scientic math as manually and also the math function can operate on arrays.

In [14]:
np.pi

3.141592653589793

In [15]:
np.e?

In [16]:
# Calculate the sine function
sin_t = np.sin(30*np.pi/180)
print(sin_t)

0.49999999999999994


In [17]:
print(np.round(sin_t, 3))

0.5


In [18]:
sin_t = np.sin(np.array((0., 30., 45., 60., 90.))*np.pi/180)
print(sin_t)

[0.         0.5        0.70710678 0.8660254  1.        ]


In [19]:
a=np.sum(sin_t)
print(a)

3.0731321849709863


## Index and slice arrays

Indexing is how we pull individual data items out of an array. Slicing extends this process to pulling out a regular set of the items.

In [20]:
# Create an array for testing
b = np.arange(12).reshape(3, 4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
b[0]

array([0, 1, 2, 3])

In [22]:
b[0,1]

1

In [23]:
b[1,3]

7

Negative indices are also allowed, which permit indexing relative to the end of the array.

In [24]:
b[2,-1]

11

Slicing syntax is written as `start:stop[:step]`, where all numbers are optional.
- defaults: 
  - start = 0
  - stop = len(dim)
  - step = 1
- The second colon is also optional if no step is used.

It should be noted that end represents one past the last item; one can also think of it as a half open interval: `[start, end)`

In [28]:
# Get the 2nd and 3rd rows
b[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
# All rows and 3rd column
b[:, 2]

array([ 2,  6, 10])